name = "manka"
author = "kulupu pi musi Manka"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ce2ba0d159e82d7b2adafdeef64843df531af3a45603bfb952c1b53a74b39cc"

[versions]
fabric = "0.14.8"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.19", "1.19-rc2"]
